######################################################################
# Automatically generated by qmake (3.0) Thu Jul 7 21:29:12 2016
######################################################################

TEMPLATE = app
TARGET = Akai
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h logindialog.h network.h
SOURCES += main.cpp mainwindow.cpp logindialog.cpp network.cpp
LIBS += -lQt5Widgets -lQt5Network
OBJECTS_DIR=objects
MOC_DIR=objects
