######################################################################
# Automatically generated by qmake (3.0) Thu Jul 7 21:29:12 2016
######################################################################

TEMPLATE = app
TARGET = Akai
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
LIBS += -lQt5Widgets
OBJECTS_DIR=objects
MOC_DIR=objects
